- app/controllers/devise/saml_sessions_controller.rb
The IdP does not include an authenticity token in its POST request, so the SAML controller should not verify it.
> Skip CSRF from IdP

- README.md
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/saml_config.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/saml_config_spec.rb
- spec/support/sp_template.rb
Instead of requiring `idp.yml` in the application, allow custom configuration by exposing the `RubySaml::Settings`. This is primarily for configuration via environment variables, but that's not required.
`idp.yml` is still supported to not break anyone else.
Replaces #13.
> Allow SAML configuration via ENV

- lib/devise_saml_authenticatable/model.rb
I needed a way to use a different set of attribute mappings between development and production.  This modification allows the attribute_map.yml file to have a top-level "development" or "production" key, similar to the current idp.yml file behavior.  If no such key is found, it falls back to the current behavior, so this should not affect existing implementations.
> Allow customized attribute_map for different environments

- README.md
- app/controllers/devise/saml_sessions_controller.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/features/saml_authentication_spec.rb
- spec/support/idp_template.rb
- spec/support/saml_idp-saml_slo_post.html.erb
- spec/support/saml_idp_controller.rb.erb
- spec/support/sp_template.rb
Add SLO support to the plugin.
Configuring an `idp_slo_target_url` gets you basic SLO, with no verification of the logout response from the IdP.
I removed support for the `assertion_consumer_logout_service_url` because ruby-saml does not support it in the logout request.
I had to pull in lawrencepit/ruby-saml-idp#10 into the fixture IdP so that it would support SLO too. I also added a persistent session to the IdP to ensure that logout was meaningful.
---
Removed section:
> If you care about the logout response, you can configure an `assertion_consumer_logout_service_url` and handle the response there, validating it against the request UUID. I added this mainly because I felt like someone would care, but if no one does we could simplify things greatly by dropping this use case.
> SLO Support

- app/controllers/devise/saml_sessions_controller.rb
- devise_saml_authenticatable.gemspec
- lib/devise_saml_authenticatable/strategy.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
- spec/support/saml_idp_controller.rb.erb
- Adds support for encrypted assertions being set on the saml_config.
ruby-saml requires you to pass the saml_settings in at initialization
of the response object for this to work.
- Fixes expected audience endpoint.
- Permit ~> 1.0.0 of ruby-saml
- If the SAML response is valid but does not match any resource then the
strategy should return invalid.
> Upgrade ruby-saml to ~> 1.0

- README.md
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
If you add a role to a user, that new role wouldn't previously be spotted by this gem.
This changeset adds the capability to update user attributes with each authentication.
> Update user attributes on login

- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
- spec/features/saml_authentication_spec.rb
- spec/support/sp_template.rb
Follow up to #26:
> On review, I think this should be enhanced a bit.
>
> * The updates should be persisted, like they are when creating the user.
> * When subject is used as the auth value, it should be included in the update. Not every IdP includes the subject value in the attributes, so the subject might be erased if it's not included in the update.
Also added a feature spec.
> Persist updated user attributes

- .rspec
- Gemfile
- spec/features/saml_authentication_spec.rb
- spec/rails_helper.rb
- spec/support/idp_template.rb
- spec/support/rails_app.rb
- spec/support/sp_template.rb
Something changed in the dependencies of the Ruby 2.2 build on Travis and the builds are failing now. It appears to be an issue with providing input to the interactive rails templates for the feature tests. I've replaced the interactive pieces with environment variables so it can be more easily automated.
> Fix Travis failures

- app/controllers/devise/saml_sessions_controller.rb
- lib/devise_saml_authenticatable/saml_config.rb
- lib/devise_saml_authenticatable/strategy.rb
- spec/devise_saml_authenticatable/saml_config_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
Lazy-load the SAML config to avoid issues with before_filter ordering.
Devise [uses `prepend_before_filter`](https://github.com/plataformatec/devise/blob/v3.5.3/app/controllers/devise/sessions_controller.rb#L4) which ends up calling `after_sign_out_path_for`, which [in this gem](https://github.com/apokalipto/devise_saml_authenticatable/blob/f4ee1cf4b4105856dec38db5313bd3ea8cf91491/app/controllers/devise/saml_sessions_controller.rb#L45) uses the SAML config. If it hasn't been retrieved yet, it blows up.
> Lazy-load SAML config

- lib/devise_saml_authenticatable/model.rb
As per the discussion in #45 this removes the `update_with_password` and `update_without_password` methods which conflict with `devise_database_authenticatable` causing database users to not be able to reset/update their password or any updates that require the password (i.e. an email on a user model). There were no tests covering these methods and no other specs failed.
> Remove methods that conflict with devise_database_authenticatable

- Gemfile
- spec/support/idp_template.rb
- spec/support/saml_idp_controller.rb.erb
- spec/support/sp_template.rb
Ruby 1.9 and 2.0 are left out of the bright Rails and Devise future, so we need to lock down their versions when testing against those old Rubies.
> Fix acceptance tests for older Rubies

- lib/devise_saml_authenticatable/strategy.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
Updates in the 1.3.0 version of ruby-saml improved the validation around SAML requests (https://github.com/onelogin/ruby-saml/pull/326).  This caused a bit of headache as new validation errors were causing our application to not authenticate.  It also surfaced the fact that validation errors are not being logged so it was near impossible to determine the source of the problem without deep diving.  This update reorganizes the authentication logic and ensures that errors are logged appropriately.
> Authentication error logging

- app/controllers/devise/saml_sessions_controller.rb
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- lib/devise_saml_authenticatable/strategy.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/model_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
Add `saml_relay_state` confic option which uses a lambda to generate a `RelayState` parameter for the SAML AuthRequest from the rails `request`. This `RelayState` is passed back from the IdP and is propagated back to the `authenticate_with_saml` function which can be used for context when authenticating the user
> RelayState option

- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- lib/devise_saml_authenticatable/saml_mapped_attributes.rb
- lib/devise_saml_authenticatable/saml_response.rb
- spec/devise_saml_authenticatable/model_spec.rb
Partly addresses https://github.com/apokalipto/devise_saml_authenticatable/issues/38
This PR introduces a mechanism to apply custom behaviour prior to saving
a resource. This behaviour occurs when `Devise.saml_update_user` or
`Devise.saml_create_user` has been enabled, and the resource has been
found or created. The mechanism works by means of introducing a hook
just prior to saving the resource, providing an application the
flexibility to make arbitrary changes to the resource.
This hook replaces the existing `set_user_saml_attributes` with a
default hook implementation which can be replaced or extended depending
on the application needs.
The changes are backward compatible to my knowledge, public
configuration has not been modified, but a new configuration has been
introduced …
> Add hooks before saving resource

- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
As part of a project, I have been leveraging the gem's support for multiple IdPs, as we allow our users to configure their own IdPs to integrate with our system. Consequently when resolving users, it is not enough for us to just use one attribute to determine if a user exists in our system, as distinct users with the same usernames could exist in different IdPs.
For our purposes, we need to use something similar to
```User.where(username: auth_value, sso: saml_response.raw_response.destination)```
to resolve our users.
This PR adds a `saml_resource_locator` hook, which can convert the User model, SAML response and auth_value into either a pre-existing user, or `nil` if none already exists.
It also includes a `saml_default_resource_locator` which preserves existing resolution behaviour for …
> Add hook to resolve user object from saml response

- .travis.yml
- app/controllers/devise/saml_sessions_controller.rb
- spec/support/Gemfile.rails5
- spec/support/idp_template.rb
- spec/support/rails_app.rb
- spec/support/saml_idp_controller.rb.erb
- spec/support/sp_template.rb
Looks like adding support for Rails 5 actually broke support for Rails 4. `skip_before_filter ..., raise: false` is supposed to be benign for older Rails versions but it's actually not skipped. See Shopify/shopify_app#304 for more on the same issue.
Running the test applications in production mode exposes the issue. I added a version check like Shopify/shopify_app#315 did.
Incidentally, this can also add support for Rails 5.1 by using `skip_before_action` instead of `skip_before_filter` 👍 
Fixes #91.
> Support Rails 4 and 5.1

- devise_saml_authenticatable.gemspec
I noticed this was missing while running an automated license audit.
> Add license to gemspec

- .travis.yml
- spec/support/Gemfile.rails4
- spec/support/Gemfile.ruby-saml-1.3
We're still supporting Ruby 1.9 and Ruby 2.0, but more and more gems aren't. 
This PR pins those gems to old versions of `public_suffix` for old Rubies, and updates the included bundler to avoid an issue there.
> Fix specs for older Ruby versions

- README.md
- lib/devise_saml_authenticatable/default_idp_entity_id_reader.rb
- lib/devise_saml_authenticatable/strategy.rb
Issue #73 identifies a problem with decrypting communication from the IdP: the certificate and private key are not passed to ruby-saml. @kevinmtrowbridge proposed a patch that got incorporated into a fork but never, apparently, this project.
This branch incorporates that code and adds two lines to `README.md` describing how it can be used even when the application uses an adapter to support multiple IdPs.
While this work eliminates some problems, the issue is not completely fixed: if there are multiple IdPs and the encryption settings are different for different providers, some other mechanism will be necessary to ensure the correct values are present in `Devise.saml_config`.
> Pass encryption settings to ruby-saml

- .travis.yml
- spec/features/saml_authentication_spec.rb
- spec/rails_helper.rb
- spec/support/Gemfile.rails5.1
- spec/support/idp_template.rb
- spec/support/rails_app.rb
- spec/support/sp_template.rb
- Bootsnap doesn't work with templates that rely on installed gems, because it caches load paths before the gems are installed.
- Migrations are run using a different class & method
- Secrets were replaced with credentials, which come with a `secret_key_base` already in place
> Support Rails 5.2 in specs

- README.md
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/routes.rb
**PR Summary**
This PR changes the `ActionDispatch::Routing::Mapper#devise_saml_authenticatable` behavior.
**Problem summary**
* Before this change, routes for `devise_saml_authenticatable` would conflict with Devise's own `database_authenticatable` routes when starting up the server:
```
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:538:in `add_route': Invalid route name, already in use: 'new_user_session'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```
* …
> add SAML routes with multiple strategies in mind

- lib/devise_saml_authenticatable/exception.rb
For more details:
https://www.honeybadger.io/blog/ruby-exception-vs-standarderror-whats-the-difference/
https://thoughtbot.com/blog/rescue-standarderror-not-exception
> SamlException inherits from StandardError instead of Exception

- README.md
ruby-saml allows for adding a configuration for clock drift. The place that this gets called in devise_saml_authenticatable is in devise_saml_authenticatable/lib/devise_saml_authenticatable/strategy.rb:40. 
As we were having a problem with clock drift, it seemed like having an easy place to configure this in this gem made the most sense. 
There were 24 failing tests but I can't imagine that was a result of my change.
Finished in 9 minutes 13 seconds (files took 31.96 seconds to load)
109 examples, 24 failures
> Added a configuration for clock drift

- .travis.yml
- app/controllers/devise/saml_sessions_controller.rb
- spec/features/saml_authentication_spec.rb
- spec/support/idp_settings_adapter.rb.erb
- spec/support/rails_app.rb
- Execute rails using correct version
- Rails 6 introduced version conflicts with earlier versions, specifically in sqlite3
- Correct use of status symbol in Rails 6
- Ruby 2.2 cannot run the latest Rails 5.2, so allow that to fail
- Fix some tests that fail due to followed redirects in Capybara
> Test fixes

- .travis.yml
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/support/Gemfile.rails5.2
- spec/support/sp_template.rb
Continue to support Rails 4 in the tests, but we may want to drop support at one point now that we're straddling three major versions.
> Add Rails 6 testing

- Gemfile
- README.md
- lib/devise_saml_authenticatable/version.rb
- spec/support/Gemfile.rails4
- spec/support/Gemfile.rails5
- spec/support/Gemfile.rails5.1
- spec/support/Gemfile.rails5.2
Typically @apokalipto bumps the version right before releasing this gem to rubygems. I haven't heard from him in a while though, so let's just update the README to use GitHub for installation.
Since we're updating installation instructions to use Github directly, I also bumped the version so it's obviously newer than what's on rubygems.
Fixes #169.
> Install from GitHub

- app/controllers/devise/saml_sessions_controller.rb
For issue #173, support metadata for multiple IdPs
> add params to metadata action to fix multi IdPs issue

- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
This PR is for issue #144 
When creating or updating the resource raises an Exception, return nil from method authenticate_with_saml to fail the authetication
> return nil when creating/updating resource raises an exception

- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
This public method was removed in #162, released in 1.6.0, which should not have included a breaking change. I put the method back and added a test to make sure it's not accidentally removed again.
Fixes #178. cc @jasonpoll
> Replace Model::attribute_map method

- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
This reverts commit 773b511c3e78c74e7ba29742923d3d0a637dbc20.
Based on the conversation in https://github.com/apokalipto/devise_saml_authenticatable/issues/181, it seems like we might want to revert this commit so it won't mask future unforeseen errors. We should be able to either use the combination of inheriting `Devise::SamlSessionsController` and `rescue_from`, or the solution in https://github.com/apokalipto/devise_saml_authenticatable/issues/182#issuecomment-698392327.
cc @luke-zhou
> Revert "return nil when creating/updating resource raises an exception"

- README.md
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- lib/devise_saml_authenticatable/saml_config.rb
- spec/features/saml_authentication_spec.rb
- spec/support/sp_template.rb
Rails 6 introduces the zeitwerk autoloader, and is warning us that using constants during initialization is not supported.
We can avoid that by setting class *names* instead of the constants directly, and loading the constants at runtime.
Fixes #172.
> Use strings for class names

- app/controllers/devise/saml_sessions_controller.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
Context: If user clear session their self and then click logout button, the error page is displayed
Explain: 
- Devise::SessionsController already has `prepend_before_action :verify_signed_out_user, only: :destroy`
but Devise::SamlSessionsController < Devise::SessionsController has `prepend_before_action :store_info_for_sp_initiated_logout, only: :destroy`
-> the order is `store_info_for_sp_initiated_logout` -> `verify_signed_out_user` -> `destroy`
- when current user is not existed, the `store_info_for_sp_initiated_logout` will raise error when try to call `Devise.saml_name_identifier_retriever.call(current_user)` (line 62)
Solution: call `verify_signed_out_user` before `store_info_for_sp_initiated_logout`
> Check user signed in before init sp logout

- README.md
- app/controllers/devise/saml_sessions_controller.rb
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/strategy.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
The `InResponseTo` attribute associates a given assertion to a given authentication request, and according to the [SAML 2.0 CORE specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) (section 3.2.2), it's required in any SAML response generated in response to a request. `ruby-saml` [will validate the `InResponseTo` attribute](https://github.com/onelogin/ruby-saml/blob/b55733fd64a559de81ad936b69cd1e9b754c40a8/lib/onelogin/ruby-saml/response.rb#L594-L606) for us if we pass `OneLogin::RubySaml::Response` a non-nil `matches_request_id` parameter when we initialize it.
This PR validates `InResponseTo` headers in SAML responses when the service provider opts-in via configuration. It does so by persisting the ID for the SAML request in the user's session and then …
> Validate `InResponseTo` header in SAML responses

- README.md
ruby-saml 1.4.3 is so old the documentation stopped to mention the update process to it, so removing the comment that mention it
> Update README to remove outdated comment

- .github/workflows/ci.yml
- Gemfile
- spec/features/saml_authentication_spec.rb
- spec/support/Gemfile.rails6
- spec/support/idp_template.rb
- spec/support/sp_template.rb
This PR adds Ruby 3.0 and 3.1 to CI and updates the CI Ruby/Rails matrix accordingly. Changes outside of the workflow definition include:
* Adding an explicit gem webrick line to the Gemfile(s) when the Ruby version is 3.0 or greater
* Adding explicit lines for net-smtp, net-imap, and net-pop when the Ruby version is 3.1 or greater to both relevant Gemfiles and the IDP template file.
This PR doesn't include Rails 7, as getting that working properly requires a bit more work with views and UI behavior.
> Add Ruby 3.0 and 3.1 to CI

- Gemfile
- spec/features/saml_authentication_spec.rb
- spec/support/Gemfile.rails5.2
- spec/support/Gemfile.rails6
PhantomJS is inactive as a project, so we should move to Chromedriver.
> Switch from phantomjs/poltergeist to selenium/chromedriver

- .github/workflows/ci.yml
- app/controllers/devise/saml_sessions_controller.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/support/Gemfile.rails6.1
- spec/support/idp_template.rb
- spec/support/rails_app.rb
- spec/support/saml_idp_controller.rb.erb
Add Rails 7 to CI and get Rails 7 working.  This involved:
* Using an updated mock IDP library
* Updating the rails new settings in test so the asset pipeline is not required
* Explicitly allowing some redirects to redirect to external URLs
Note that this last item involves actual production code changes, meaning that a new gem version will need to be released to properly support Rails 7.
In addition to the above Rubocop did some minor reformatting.
> Rails 7 Support

- README.md
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- spec/devise_saml_authenticatable/model_spec.rb
Solve https://github.com/apokalipto/devise_saml_authenticatable/issues/203.
Sorry for the late PRs. I haven't had any free time lately, and the priority for this feature in our system is not that high.
This PR let `saml_create_user` and `saml_update_user` accept a Proc as value. 
The model class, saml response and auth_value are passed to the proc so that finer-grained decisions can be made.
> Allow proc as value for saml_create_user and saml_update_user

- README.md
- app/controllers/devise/saml_sessions_controller.rb
- lib/devise_saml_authenticatable/saml_config.rb
- lib/devise_saml_authenticatable/strategy.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
In applications where the domain name can change, the use of the ActionController `request` object is required so the SP url can be set dynamically.
This change makes it so the `request` object can optionally be passed to the `IdPSettingsAdapter#settings` method so urls can be created dynamically.
> Pass controller request object to idp settings adapter

- README.md
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/saml_config_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
- spec/support/idp_settings_adapter.rb.erb
- spec/support/sp_template.rb
The method sp_entity_id was introduced, and issuer deprecated, in ruby-saml version 1.11. References are contained only in docs and test code.
Note that `DefaultIdpEntityIdReader` uses `OneLogin::RubySaml::SloLogoutrequest#issuer`, a distinct and still valid method.
> Replace deprecated OneLogin::RubySaml::Settings#issuer with sp_entity_id

- lib/devise_saml_authenticatable/saml_config.rb
- spec/devise_saml_authenticatable/saml_config_spec.rb
This should remove the `devise_saml_authenticatable/saml_config.rb:17: warning: File.exists? is deprecated; use File.exist? instead`warnings that are output in tests and server logs
> Update File.exists? reference

- .github/workflows/ci.yml
- spec/devise_saml_authenticatable/model_spec.rb
To get the specs to pass I had to add explicit hashes to the `with` clauses, so they would be properly disambiguated from keyword arguments.
This runs green on my fork.
> Adds Ruby 3.2 to the CI matrix

- .github/workflows/ci.yml
Remove old Rubies and Rails, and add the latest Ruby
Rails maintenance policy: https://guides.rubyonrails.org/maintenance_policy.html
Ruby stable releases: https://www.ruby-lang.org/en/downloads/
> Update build matrix for EOL

- devise_saml_authenticatable.gemspec
Hello everyone 👋 
The following security vulnerability was recently discovered [CVE-2024-4540](https://www.cve.org/CVERecord?id=CVE-2024-4540)
A new version of ruby-saml, containing a fix for this bug, was released a couple of days ago: [changelog](https://github.com/SAML-Toolkits/ruby-saml/releases/tag/v1.17.0)
This PR bumps the ruby-saml dependency to the [version](https://github.com/SAML-Toolkits/ruby-saml/releases/tag/v1.17.0) that contains the fix.
Please let me know if you need more informations...
Thank you!
> Bump ruby-saml to v1.17.0 to fix CVE-2024-4540

- README.md
- app/controllers/devise/saml_sessions_controller.rb
- lib/devise_saml_authenticatable.rb
- lib/devise_saml_authenticatable/model.rb
- lib/devise_saml_authenticatable/strategy.rb
- spec/controllers/devise/saml_sessions_controller_spec.rb
- spec/devise_saml_authenticatable/strategy_spec.rb
- spec/support/saml_idp_controller.rb.erb
> Store IDP session index in session to allow multiple sessions per user
